// Generated by scripts/src/generate_index.ts
// DO NOT EDIT MANUALLY
import type { ConceptIndex } from '@/types/micro';

export const GENERATED_CONCEPT_INDEX: ConceptIndex = {
    "array.contiguous-memory": [
        {
            "href": "/learn/dsa/arrays",
            "title": "Arrays",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": true
        },
        {
            "href": "/session/practice/415",
            "title": "Add Strings",
            "type": "practice",
            "estMinutes": 10,
            "isPrimary": true
        },
        {
            "href": "/session/practice/408",
            "title": "Valid Word Abbreviation",
            "type": "practice",
            "estMinutes": 10,
            "isPrimary": true
        },
        {
            "href": "/session/practice/1424",
            "title": "Diagonal Traverse II",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/134",
            "title": "Gas Station",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/325",
            "title": "Maximum Size Subarray Sum Equals k",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/31",
            "title": "Next Permutation",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/151",
            "title": "Reverse Words in a String",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/54",
            "title": "Spiral Matrix",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        }
    ],
    "array.dynamic-resizing": [
        {
            "href": "/learn/dsa/efficient-string-building",
            "title": "Efficient String Building",
            "type": "learn",
            "estMinutes": 3,
            "isPrimary": true
        }
    ],
    "array.random-access-o1": [
        {
            "href": "/learn/dsa/arrays",
            "title": "Arrays",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": false
        }
    ],
    "backtracking.search": [
        {
            "href": "/learn/dsa/backtracking",
            "title": "Backtracking",
            "type": "learn",
            "estMinutes": 4,
            "isPrimary": true
        },
        {
            "href": "/session/practice/216",
            "title": "Combination Sum III",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/77",
            "title": "Combinations",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/17",
            "title": "Letter Combinations of a Phone Number",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/46",
            "title": "Permutations",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/51",
            "title": "N-Queens",
            "type": "practice",
            "estMinutes": 20,
            "isPrimary": true
        },
        {
            "href": "/session/practice/37",
            "title": "Sudoku Solver",
            "type": "practice",
            "estMinutes": 20,
            "isPrimary": true
        }
    ],
    "big-o.amortized-analysis": [
        {
            "href": "/learn/dsa/efficient-string-building",
            "title": "Efficient String Building",
            "type": "learn",
            "estMinutes": 3,
            "isPrimary": false
        }
    ],
    "big-o.time-complexity": [
        {
            "href": "/learn/dsa/templates",
            "title": "Templates",
            "type": "learn",
            "estMinutes": 7,
            "isPrimary": true
        },
        {
            "href": "/learn/dsa/stacks",
            "title": "Stacks",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": false
        },
        {
            "href": "/learn/dsa/queues",
            "title": "Queues",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": false
        }
    ],
    "binary-search.technique": [
        {
            "href": "/learn/dsa/binary-search",
            "title": "Binary Search",
            "type": "learn",
            "estMinutes": 7,
            "isPrimary": true
        },
        {
            "href": "/session/practice/528",
            "title": "Random Pick with Weight",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/74",
            "title": "Search a 2D Matrix",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        }
    ],
    "career.behavioral": [
        {
            "href": "/learn/dsa/how-to-prepare-for-behavioural-interviews",
            "title": "How to Prepare for Behavioural Interviews",
            "type": "learn",
            "estMinutes": 3,
            "isPrimary": true
        }
    ],
    "career.learning": [
        {
            "href": "/learn/dsa/ive-uploaded-everything-i-know",
            "title": "I've Uploaded Everything I Know",
            "type": "learn",
            "estMinutes": 3,
            "isPrimary": true
        }
    ],
    "career.resume": [
        {
            "href": "/learn/dsa/how-to-write-a-resume-for-software-engineering-roles",
            "title": "How to Write a Resume for Software Engineering Roles",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": true
        }
    ],
    "career.strategy": [
        {
            "href": "/learn/dsa/how-to-get-good-at-leetcode",
            "title": "How to Get Good at LeetCode",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": true
        },
        {
            "href": "/learn/dsa/what-30-days-of-competitive-programming-taught-me",
            "title": "What 30 Days of Competitive Programming Taught Me",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": true
        }
    ],
    "dp.memoization": [
        {
            "href": "/learn/dsa/dynamic-programming-top-down",
            "title": "Dynamic Programming (Top-Down Memo)",
            "type": "learn",
            "estMinutes": 4,
            "isPrimary": true
        },
        {
            "href": "/session/practice/746",
            "title": "Min Cost Climbing Stairs",
            "type": "practice",
            "estMinutes": 10,
            "isPrimary": true
        },
        {
            "href": "/session/practice/1155",
            "title": "Number of Dice Rolls With Target Sum",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/96",
            "title": "Unique Binary Search Trees",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        }
    ],
    "fast-slow-pointers.cycle-detection": [
        {
            "href": "/learn/dsa/fast-and-slow-pointer",
            "title": "Fast and Slow Pointer",
            "type": "learn",
            "estMinutes": 4,
            "isPrimary": true
        },
        {
            "href": "/session/practice/876",
            "title": "Middle of the Linked List",
            "type": "practice",
            "estMinutes": 10,
            "isPrimary": true
        },
        {
            "href": "/session/practice/142",
            "title": "Linked List Cycle II",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        }
    ],
    "graph.representation": [
        {
            "href": "/session/practice/721",
            "title": "Accounts Merge",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/547",
            "title": "Number of Provinces",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/1101",
            "title": "The Earliest Moment When Everyone Become Friends",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/1361",
            "title": "Validate Binary Tree Nodes",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/learn/dsa/graphs",
            "title": "Graphs",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": false
        }
    ],
    "graph.shortest-path-dijkstra": [
        {
            "href": "/learn/dsa/dijkstra",
            "title": "Dijkstra's Algorithm",
            "type": "learn",
            "estMinutes": 4,
            "isPrimary": true
        }
    ],
    "graph.terminology": [
        {
            "href": "/learn/dsa/graphs",
            "title": "Graphs",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": true
        },
        {
            "href": "/session/practice/2385",
            "title": "Amount of Time for Binary Tree to Be Infected",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/787",
            "title": "Cheapest Flights Within K Stops",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/743",
            "title": "Network Delay Time",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/200",
            "title": "Number of Islands",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/505",
            "title": "The Maze II",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/286",
            "title": "Walls and Gates",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/815",
            "title": "Bus Routes",
            "type": "practice",
            "estMinutes": 20,
            "isPrimary": true
        },
        {
            "href": "/session/practice/827",
            "title": "Making A Large Island",
            "type": "practice",
            "estMinutes": 20,
            "isPrimary": true
        },
        {
            "href": "/session/practice/317",
            "title": "Shortest Distance from All Buildings",
            "type": "practice",
            "estMinutes": 20,
            "isPrimary": true
        }
    ],
    "graph.traversal-bfs": [
        {
            "href": "/learn/dsa/bfs",
            "title": "BFS (Breadth-First Search)",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": true
        },
        {
            "href": "/learn/dsa/graphs",
            "title": "Graphs",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": false
        }
    ],
    "graph.traversal-dfs": [
        {
            "href": "/learn/dsa/dfs",
            "title": "DFS (Depth-First Search)",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": true
        },
        {
            "href": "/session/practice/269",
            "title": "Alien Dictionary",
            "type": "practice",
            "estMinutes": 20,
            "isPrimary": true
        },
        {
            "href": "/session/practice/631",
            "title": "Design Excel Sum Formula",
            "type": "practice",
            "estMinutes": 20,
            "isPrimary": true
        },
        {
            "href": "/learn/dsa/graphs",
            "title": "Graphs",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": false
        }
    ],
    "hash.collision-handling": [
        {
            "href": "/session/practice/1",
            "title": "Two Sum",
            "type": "practice",
            "estMinutes": 10,
            "isPrimary": true
        },
        {
            "href": "/session/practice/49",
            "title": "Group Anagrams",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/380",
            "title": "Insert Delete GetRandom O(1)",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/2260",
            "title": "Minimum Consecutive Cards to Pick Up",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/1010",
            "title": "Pairs of Songs With Total Durations Divisible by 60",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/981",
            "title": "Time Based Key-Value Store",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/learn/dsa/hash-maps-and-sets",
            "title": "Hash Maps and Sets",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": false
        }
    ],
    "hash.o1-average-lookup": [
        {
            "href": "/learn/dsa/hash-maps-and-sets",
            "title": "Hash Maps and Sets",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": true
        },
        {
            "href": "/learn/dsa/subarrays-with-exact-k",
            "title": "Subarrays with Exact K",
            "type": "learn",
            "estMinutes": 4,
            "isPrimary": false
        }
    ],
    "hash.space-time-tradeoff": [
        {
            "href": "/learn/dsa/hash-maps-and-sets",
            "title": "Hash Maps and Sets",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": false
        }
    ],
    "heap.priority-queue": [
        {
            "href": "/learn/dsa/top-k-heap",
            "title": "Top K with Heap",
            "type": "learn",
            "estMinutes": 3,
            "isPrimary": true
        },
        {
            "href": "/learn/dsa/heaps",
            "title": "Heaps",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": true
        }
    ],
    "list.insertion-o1-known": [
        {
            "href": "/learn/dsa/linked-lists",
            "title": "Linked Lists",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": false
        }
    ],
    "list.pointer-invariants": [
        {
            "href": "/learn/dsa/linked-lists",
            "title": "Linked Lists",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": true
        },
        {
            "href": "/session/practice/21",
            "title": "Merge Two Sorted Lists",
            "type": "practice",
            "estMinutes": 10,
            "isPrimary": true
        },
        {
            "href": "/session/practice/2",
            "title": "Add Two Numbers",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/146",
            "title": "LRU Cache",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/143",
            "title": "Reorder List",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/432",
            "title": "All O`one Data Structure",
            "type": "practice",
            "estMinutes": 20,
            "isPrimary": true
        }
    ],
    "list.singly-vs-doubly": [
        {
            "href": "/learn/dsa/linked-lists",
            "title": "Linked Lists",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": false
        }
    ],
    "list.traversal-cost": [
        {
            "href": "/learn/dsa/linked-lists",
            "title": "Linked Lists",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": false
        }
    ],
    "math.prefix-sum": [
        {
            "href": "/learn/dsa/prefix-sum",
            "title": "Prefix Sum",
            "type": "learn",
            "estMinutes": 3,
            "isPrimary": true
        },
        {
            "href": "/learn/dsa/subarrays-with-exact-k",
            "title": "Subarrays with Exact K",
            "type": "learn",
            "estMinutes": 4,
            "isPrimary": true
        }
    ],
    "matrix.sparse": [
        {
            "href": "/learn/dsa/sparse-tables",
            "title": "Sparse Tables",
            "type": "learn",
            "estMinutes": 7,
            "isPrimary": true
        }
    ],
    "queue.bfs-relationship": [
        {
            "href": "/learn/dsa/bfs",
            "title": "BFS (Breadth-First Search)",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": false
        },
        {
            "href": "/learn/dsa/queues",
            "title": "Queues",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": false
        }
    ],
    "queue.fifo-model": [
        {
            "href": "/learn/dsa/queues",
            "title": "Queues",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": true
        }
    ],
    "recursion.base-case": [
        {
            "href": "/learn/dsa/dfs",
            "title": "DFS (Depth-First Search)",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": false
        }
    ],
    "segment-tree.range-query": [
        {
            "href": "/learn/dsa/binary-indexed-trees",
            "title": "Binary Indexed Trees",
            "type": "learn",
            "estMinutes": 7,
            "isPrimary": true
        },
        {
            "href": "/learn/dsa/segment-trees",
            "title": "Segment Trees",
            "type": "learn",
            "estMinutes": 7,
            "isPrimary": true
        }
    ],
    "sliding-window.technique": [
        {
            "href": "/learn/dsa/sliding-window",
            "title": "Sliding Window",
            "type": "learn",
            "estMinutes": 4,
            "isPrimary": true
        },
        {
            "href": "/session/practice/904",
            "title": "Fruit Into Baskets",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        }
    ],
    "stack.call-stack-relationship": [
        {
            "href": "/learn/dsa/stacks",
            "title": "Stacks",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": false
        }
    ],
    "stack.lifo-model": [
        {
            "href": "/learn/dsa/stacks",
            "title": "Stacks",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": true
        },
        {
            "href": "/session/practice/155",
            "title": "Min Stack",
            "type": "practice",
            "estMinutes": 10,
            "isPrimary": true
        },
        {
            "href": "/session/practice/735",
            "title": "Asteroid Collision",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/227",
            "title": "Basic Calculator II",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/921",
            "title": "Minimum Add to Make Parentheses Valid",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        }
    ],
    "stack.monotonic": [
        {
            "href": "/learn/dsa/monotonic-stack",
            "title": "Monotonic Stack",
            "type": "learn",
            "estMinutes": 4,
            "isPrimary": true
        },
        {
            "href": "/session/practice/739",
            "title": "Daily Temperatures",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/84",
            "title": "Largest Rectangle in Histogram",
            "type": "practice",
            "estMinutes": 20,
            "isPrimary": true
        },
        {
            "href": "/session/practice/1944",
            "title": "Number of Visible People in a Queue",
            "type": "practice",
            "estMinutes": 20,
            "isPrimary": true
        }
    ],
    "system.caching": [
        {
            "href": "/learn/dsa/caching",
            "title": "Caching",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": true
        }
    ],
    "system.cap-theorem": [
        {
            "href": "/learn/dsa/cap-theorem",
            "title": "CAP Theorem",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": true
        }
    ],
    "system.communication": [
        {
            "href": "/learn/dsa/apis",
            "title": "APIs",
            "type": "learn",
            "estMinutes": 2,
            "isPrimary": true
        },
        {
            "href": "/learn/dsa/simple-client-server-architecture",
            "title": "Simple Client-Server Architecture",
            "type": "learn",
            "estMinutes": 2,
            "isPrimary": true
        },
        {
            "href": "/learn/dsa/batch-vs-stream-processing",
            "title": "Batch vs Stream Processing",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": true
        },
        {
            "href": "/learn/dsa/message-queues",
            "title": "Message Queues",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": true
        }
    ],
    "system.consistency": [
        {
            "href": "/learn/dsa/acid-and-base",
            "title": "ACID and BASE",
            "type": "learn",
            "estMinutes": 4,
            "isPrimary": true
        }
    ],
    "system.load-balancing": [
        {
            "href": "/learn/dsa/load-balancer",
            "title": "Load Balancer",
            "type": "learn",
            "estMinutes": 3,
            "isPrimary": true
        }
    ],
    "system.observability": [
        {
            "href": "/learn/dsa/observability-and-developer-experience",
            "title": "Observability and Developer Experience",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": true
        }
    ],
    "system.partitioning": [
        {
            "href": "/learn/dsa/data-partitioning",
            "title": "Data Partitioning",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": true
        }
    ],
    "system.replication": [
        {
            "href": "/learn/dsa/database-replication",
            "title": "Database Replication",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": true
        }
    ],
    "system.requirements": [
        {
            "href": "/learn/dsa/requirements-gathering",
            "title": "Requirements Gathering",
            "type": "learn",
            "estMinutes": 1,
            "isPrimary": true
        },
        {
            "href": "/learn/dsa/establishing-a-baseline",
            "title": "Establishing a Baseline",
            "type": "learn",
            "estMinutes": 3,
            "isPrimary": true
        }
    ],
    "system.scalability": [
        {
            "href": "/learn/dsa/system-characteristics",
            "title": "System Characteristics",
            "type": "learn",
            "estMinutes": 3,
            "isPrimary": true
        },
        {
            "href": "/learn/dsa/vertical-scaling-versus-horizontal-scaling",
            "title": "Vertical Scaling versus Horizontal Scaling",
            "type": "learn",
            "estMinutes": 3,
            "isPrimary": true
        },
        {
            "href": "/learn/dsa/stateless-vs-stateful-servers",
            "title": "Stateless vs Stateful Web Servers",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": true
        },
        {
            "href": "/learn/dsa/establishing-a-baseline",
            "title": "Establishing a Baseline",
            "type": "learn",
            "estMinutes": 3,
            "isPrimary": false
        },
        {
            "href": "/learn/dsa/data-centers-and-regions",
            "title": "Data Centers and Regions",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": false
        }
    ],
    "system.storage": [
        {
            "href": "/learn/dsa/databases",
            "title": "Databases",
            "type": "learn",
            "estMinutes": 3,
            "isPrimary": true
        },
        {
            "href": "/learn/dsa/data-centers-and-regions",
            "title": "Data Centers and Regions",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": true
        }
    ],
    "tree.parent-child-model": [
        {
            "href": "/learn/dsa/trees",
            "title": "Trees",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": true
        }
    ],
    "tree.properties": [
        {
            "href": "/session/practice/993",
            "title": "Cousins in Binary Tree",
            "type": "practice",
            "estMinutes": 10,
            "isPrimary": true
        },
        {
            "href": "/session/practice/543",
            "title": "Diameter of Binary Tree",
            "type": "practice",
            "estMinutes": 10,
            "isPrimary": true
        },
        {
            "href": "/session/practice/515",
            "title": "Find Largest Value in Each Tree Row",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/973",
            "title": "K Closest Points to Origin",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/236",
            "title": "Lowest Common Ancestor of a Binary Tree",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/253",
            "title": "Meeting Rooms II",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/129",
            "title": "Sum Root to Leaf Numbers",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/347",
            "title": "Top K Frequent Elements",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/98",
            "title": "Validate Binary Search Tree",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/23",
            "title": "Merge k Sorted Lists",
            "type": "practice",
            "estMinutes": 20,
            "isPrimary": true
        },
        {
            "href": "/session/practice/297",
            "title": "Serialize and Deserialize Binary Tree",
            "type": "practice",
            "estMinutes": 20,
            "isPrimary": true
        },
        {
            "href": "/session/practice/428",
            "title": "Serialize and Deserialize N-ary Tree",
            "type": "practice",
            "estMinutes": 20,
            "isPrimary": true
        },
        {
            "href": "/learn/dsa/trees",
            "title": "Trees",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": false
        }
    ],
    "tree.traversal-orders": [
        {
            "href": "/learn/dsa/trees",
            "title": "Trees",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": false
        }
    ],
    "trie.prefix-tree": [
        {
            "href": "/learn/dsa/tries",
            "title": "Tries",
            "type": "learn",
            "estMinutes": 6,
            "isPrimary": true
        },
        {
            "href": "/session/practice/1268",
            "title": "Search Suggestions System",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/588",
            "title": "Design In-Memory File System",
            "type": "practice",
            "estMinutes": 20,
            "isPrimary": true
        }
    ],
    "two-pointers.technique": [
        {
            "href": "/learn/dsa/two-pointers",
            "title": "Two Pointers",
            "type": "learn",
            "estMinutes": 4,
            "isPrimary": true
        },
        {
            "href": "/session/practice/160",
            "title": "Intersection of Two Linked Lists",
            "type": "practice",
            "estMinutes": 10,
            "isPrimary": true
        },
        {
            "href": "/session/practice/283",
            "title": "Move Zeroes",
            "type": "practice",
            "estMinutes": 10,
            "isPrimary": true
        },
        {
            "href": "/session/practice/167",
            "title": "Two Sum II - Input Array Is Sorted",
            "type": "practice",
            "estMinutes": 10,
            "isPrimary": true
        },
        {
            "href": "/session/practice/680",
            "title": "Valid Palindrome II",
            "type": "practice",
            "estMinutes": 10,
            "isPrimary": true
        },
        {
            "href": "/session/practice/16",
            "title": "3Sum Closest",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        },
        {
            "href": "/session/practice/75",
            "title": "Sort Colors",
            "type": "practice",
            "estMinutes": 15,
            "isPrimary": true
        }
    ],
    "union-find.disjoint-set": [
        {
            "href": "/learn/dsa/union-find",
            "title": "Union Find",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": true
        }
    ]
};
