// Generated by scripts/src/generate_index.ts
// DO NOT EDIT MANUALLY
import type { ConceptIndex } from '@/types/micro';

export const GENERATED_CONCEPT_INDEX: ConceptIndex = {
    "array.contiguous-memory": [
        {
            "href": "/learn/dsa/arrays",
            "title": "Arrays",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": true
        }
    ],
    "array.random-access-o1": [
        {
            "href": "/learn/dsa/arrays",
            "title": "Arrays",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": false
        }
    ],
    "big-o.time-complexity": [
        {
            "href": "/learn/dsa/templates",
            "title": "Templates",
            "type": "learn",
            "estMinutes": 7,
            "isPrimary": true
        }
    ],
    "graph.traversal-bfs": [
        {
            "href": "/learn/dsa/graphs",
            "title": "Graphs",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": true
        }
    ],
    "graph.traversal-dfs": [
        {
            "href": "/learn/dsa/graphs",
            "title": "Graphs",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": false
        }
    ],
    "list.pointer-invariants": [
        {
            "href": "/learn/dsa/linked-lists",
            "title": "Linked Lists",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": true
        }
    ],
    "list.traversal-cost": [
        {
            "href": "/learn/dsa/linked-lists",
            "title": "Linked Lists",
            "type": "learn",
            "estMinutes": 5,
            "isPrimary": false
        }
    ],
    "tree.traversal-inorder": [
        {
            "href": "/learn/dsa/trees",
            "title": "Trees",
            "type": "learn",
            "estMinutes": 4,
            "isPrimary": true
        }
    ]
};
