import { config } from 'dotenv';
config({ path: '.env.local' });
import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import path from 'path';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

if (!supabaseUrl || !supabaseKey) {
    console.error('Missing Supabase credentials. Check .env.local');
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function main() {
    console.log('--- Generating Concept Index ---');

    // Fetch all published articles
    const { data: articles, error } = await supabase
        .from('LearningArticles')
        .select('slug, title, reading_time_minutes, concept_tags, primary_concept')
        .eq('is_published', true);

    if (error || !articles) {
        console.error('Failed to fetch articles:', error?.message);
        process.exit(1);
    }

    const index: Record<string, any[]> = {};

    articles.forEach(a => {
        const tags = a.concept_tags || [];
        tags.forEach((tag: string) => {
            if (!index[tag]) index[tag] = [];

            const isPractice = a.slug.includes('practice') || a.slug.includes('quiz') || a.slug.includes('exercise');

            index[tag].push({
                href: `/learn/dsa/${a.slug}`, // Defaulting to DSA for now based on project context
                title: a.title,
                type: isPractice ? 'practice' : 'learn',
                estMinutes: a.reading_time_minutes || 5,
                isPrimary: a.primary_concept === tag
            });
        });
    });

    // Sort deterministically for stable code generation
    const sortedIndex: Record<string, any[]> = {};
    const sortedTags = Object.keys(index).sort();

    sortedTags.forEach(tag => {
        const items = index[tag];
        items.sort((a, b) => {
            // 1. Primary first
            if (a.isPrimary !== b.isPrimary) return a.isPrimary ? -1 : 1;
            // 2. Shorter estMinutes first
            if (a.estMinutes !== b.estMinutes) return a.estMinutes - b.estMinutes;
            // 3. Alphabetical title
            return a.title.localeCompare(b.title);
        });
        sortedIndex[tag] = items;
    });

    const outputDir = path.join(process.cwd(), 'src/lib');
    const outputPath = path.join(outputDir, 'concept-index.generated.ts');

    const content = `// Generated by scripts/src/generate_index.ts
// DO NOT EDIT MANUALLY
import type { ConceptIndex } from '@/types/micro';

export const GENERATED_CONCEPT_INDEX: ConceptIndex = ${JSON.stringify(sortedIndex, null, 4)};
`;

    fs.writeFileSync(outputPath, content);
    console.log(`✅ Successfully generated ${outputPath}`);
    console.log(`📊 Indexed ${articles.length} articles across ${sortedTags.length} concepts.`);
}

main().catch(console.error);
