import { EXPLOITATION_RATIO } from '@/lib/session-llm-planner/config';
import {
  formatLastInternalization,
  formatOutcomeSignals,
  formatPersonalizationProfile,
} from '@/lib/session-llm-planner/formatting';
import type { PromptInput } from '@/lib/session-llm-planner/types';

export function buildPlannerPrompt(input: PromptInput): string {
  return [
    'You are selecting a short personalized learning session plan.',
    `Track: ${input.trackName} (${input.trackSlug}).`,
    `Pick 2-${input.maxItems} items from the candidate list, but pick 1 item if quality is low.`,
    'Prefer mixing learn + practice when practice is relevant.',
    'When focused sections are available, prefer mixing sections from different articles over rereading full articles.',
    'Optimize for highest learning leverage in the next 20 minutes.',
    'Pick a concrete and ambitious next step, not a safe generic step.',
    'Hard constraints:',
    '- Only use candidate IDs exactly as provided.',
    '- No duplicate IDs.',
    '- Keep total estimated time <= 22 minutes.',
    '- If learn items exist, include at least one learn item.',
    ...(input.requirePracticeItem && input.hasPracticeCandidate
      ? ['- Include at least one practice item.']
      : []),
    '- Keep intent text causal and concrete (must include "because").',
    '- Avoid motivational fluff.',
    'Return strict JSON only with this shape:',
    '{"selected":[{"id":"candidate-id","intentType":"foundation|bridge|tradeoff|practice","intentText":"one concise causal sentence","targetConcept":"short concept label"}]}',
    'intentText must explain why this item is next and stay under 140 chars.',
    'targetConcept should be a clear label like "Pointer invariants" or "Medium interview problem solving".',
    '',
    `Recent activity titles: ${input.recentActivityTitles.join(' | ') || 'none'}`,
    `User stubborn concepts: ${input.userState?.stubbornConcepts.join(', ') || 'none'}`,
    `User recent concepts: ${input.userState?.recentConcepts.join(', ') || 'none'}`,
    `User failure modes: ${JSON.stringify(input.userState?.failureModes || [])}`,
    `User aggregate history: ${input.userState?.aggregateHistory.join(' | ') || 'none'}`,
    `Last internalization: ${formatLastInternalization(input.userState)}`,
    `Outcome signals: ${formatOutcomeSignals(input.outcomeSignals)}`,
    `Personalization profile: ${formatPersonalizationProfile(input.personalizationProfile)}`,
    `Practice target difficulty: ${input.practiceTargetDifficulty || 'none'}`,
    `Policy: target ${Math.round(EXPLOITATION_RATIO * 100)}% exploit (weak/recent/struggling concepts) and ${Math.round((1 - EXPLOITATION_RATIO) * 100)}% explore (new concepts) when feasible.`,
    '',
    'Decision rubric (must follow):',
    '- Score each candidate: leverage (0-3) + fit_to_failure_modes (0-3) + novelty (0-2) - redundancy (0-3) - time_risk (0-2).',
    '- leverage: how much skill gain per minute.',
    '- fit_to_failure_modes: directly addresses listed failure modes / stubborn concepts.',
    '- novelty: not in recentActivityTitles/recentConcepts.',
    '- redundancy: same article/concept as recent activity OR overlaps another selected item.',
    '- time_risk: likely to exceed its estimate or cause context switching.',
    '- Select highest total scores subject to constraints.',
    '',
    'Quality gating:',
    '- "Quality is low" ONLY if: (max candidate score <= 2) OR (no candidate matches failure modes/stubborn concepts AND no strong new concept exists).',
    '- If quality is low, select exactly 1 best candidate and set intentText to explain the limitation.',
    '',
    'Selection hygiene:',
    '- Before returning JSON, internally compute scores for ALL candidates and select the highest-scoring set.',
    '- If you cannot compute scores from provided fields, treat missing data as 0 and explain via intentText.',
    '',
    'Research-backed learning strategy (follow strictly):',
    '- INTERLEAVING: If selecting 2+ items, select from at least 2 different concept families. Mixing topics improves long-term retention by 50-125% vs blocked practice.',
    '- SPACED REVIEW: Prefer concepts the user has not seen in several days. Concepts seen in the last 2-3 days should be deprioritized unless no other candidates exist.',
    '- DIFFICULTY ESCALATION: For concepts the user has practiced 5+ times at medium difficulty, prefer hard problems. Research shows 1 hard problem equals ~2.3 mediums for interview readiness.',
    '',
    'Diversity & Selection rules:',
    '- If selecting 2+ items: ensure at least 2 distinct targetConcepts.',
    '- Avoid selecting 2 items from the same article unless they are different sections with clearly different targetConcepts.',
    '- If requirePracticeItem is true, practice must target a failure mode or stubborn concept when possible.',
    '- If candidates include focused_sections, prefer selecting them unless a full_article score is higher by >= 2.',
    '- Redundancy is HIGH (-3) if articleId matches a recentActivityTitles item or another selected item and targetConcept overlaps.',
    '- Redundancy is MED (-2) if candidate concepts overlap recentConcepts or stubbornConcepts but does not directly target the failure mode.',
    '',
    'Intent & Output rules:',
    '- Order selected items in the exact sequence the user should do them (highest dependency first).',
    '- intentText must reference either a failure mode/stubborn concept OR a specific gap implied by recent activity, and include "because".',
    '- intentType must be consistent: practice only if it is an actual practice item; bridge requires from->to style rationale; tradeoff only if it’s explicitly a tradeoff.',
    '',
    `Candidates: ${JSON.stringify(input.compactCandidates)}`,
  ].join('\n');
}
