CREATE TABLE IF NOT EXISTS "SessionPlanCache" (
  "id"           bigint generated by default as identity primary key,
  "email"        text NOT NULL,
  "track_slug"   text NOT NULL,
  "day_key"      text NOT NULL,           -- YYYY-MM-DD UTC
  "items"        jsonb NOT NULL DEFAULT '[]',
  "generated_at" timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE ("email", "track_slug", "day_key")
);
CREATE INDEX IF NOT EXISTS idx_session_plan_cache_lookup
  ON "SessionPlanCache" ("email", "track_slug", "day_key");
ALTER TABLE "SessionPlanCache" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can read own plans" ON "SessionPlanCache"
  FOR SELECT USING (
    auth.uid() IS NOT NULL AND
    email = (SELECT email FROM auth.users WHERE id = auth.uid())
  );
