-- Tutor conversations for AI tutor session flow

-- Ensure shared updated_at trigger function exists
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS "TutorConversations" (
  "id"          bigint generated by default as identity primary key,
  "session_id"  bigint REFERENCES public."TestSession"("id") ON DELETE CASCADE,
  "user_id"     bigint NOT NULL REFERENCES public."Users"("id") ON DELETE CASCADE,
  "article_id"  UUID REFERENCES public."LearningArticles"("id") ON DELETE SET NULL,
  "messages"    JSONB NOT NULL DEFAULT '[]',
  "created_at"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at"  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tutor_conversations_session_id ON "TutorConversations"("session_id");
CREATE INDEX IF NOT EXISTS idx_tutor_conversations_user_id ON "TutorConversations"("user_id");

-- Auto-update updated_at
CREATE OR REPLACE TRIGGER update_tutor_conversations_updated_at
  BEFORE UPDATE ON "TutorConversations"
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
