-- Drop existing functions if they have a different signature (e.g. return type)
DROP FUNCTION IF EXISTS public.get_signups_by_day_last_30();
DROP FUNCTION IF EXISTS public.get_dau_by_day_last_30();

-- UserSignIns: one row per user per calendar day for DAU
CREATE TABLE IF NOT EXISTS public."UserSignIns" (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email        text NOT NULL,
  sign_in_date date NOT NULL,
  UNIQUE (email, sign_in_date)
);

COMMENT ON TABLE public."UserSignIns" IS 'One row per user per calendar day for daily active user stats';

CREATE INDEX IF NOT EXISTS "idx_user_sign_ins_sign_in_date"
  ON public."UserSignIns" (sign_in_date);

ALTER TABLE public."UserSignIns" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role only for UserSignIns"
  ON public."UserSignIns"
  FOR ALL
  USING (false)
  WITH CHECK (false);

-- RPC for signups by day (last 30 days) — used by admin dashboard and daily brief
CREATE OR REPLACE FUNCTION public.get_signups_by_day_last_30()
RETURNS TABLE (day date, count bigint)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT date(created_at) AS day, count(*)::bigint
  FROM "Users"
  WHERE created_at >= (current_timestamp - interval '30 days')
  GROUP BY date(created_at)
  ORDER BY day;
$$;

-- RPC for daily active users by day (last 30 days)
CREATE OR REPLACE FUNCTION public.get_dau_by_day_last_30()
RETURNS TABLE (day date, count bigint)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT sign_in_date AS day, count(*)::bigint
  FROM "UserSignIns"
  WHERE sign_in_date >= (current_date - interval '30 days')
  GROUP BY sign_in_date
  ORDER BY day;
$$;
