CREATE TABLE IF NOT EXISTS "TutorRequestEvents" (
  "id"         bigint generated by default as identity primary key,
  "user_id"    bigint NOT NULL REFERENCES public."Users"("id") ON DELETE CASCADE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tutor_request_events_user_created_at
  ON "TutorRequestEvents"("user_id", "created_at");
