ALTER TABLE public."Users"
  ADD COLUMN IF NOT EXISTS weekend_off_enabled boolean NOT NULL DEFAULT false;
CREATE TABLE IF NOT EXISTS public.streak_freezes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public."Users"(id) ON DELETE CASCADE,
  used_at timestamptz NOT NULL,
  type text NOT NULL CHECK (type IN ('manual', 'weekend')),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, used_at, type)
);
CREATE INDEX IF NOT EXISTS streak_freezes_user_used_at_idx
  ON public.streak_freezes (user_id, used_at DESC);
ALTER TABLE public.streak_freezes ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'streak_freezes'
      AND policyname = 'Anyone can view their own streak freezes'
  ) THEN
    CREATE POLICY "Anyone can view their own streak freezes"
      ON public.streak_freezes
      FOR ALL
      TO public
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;
