-- =============================================================================
-- Baseline schema migration.
-- Captures all tables that were created directly in production before
-- the migrations folder was established. Safe to run multiple times
-- (all statements use IF NOT EXISTS / IF EXISTS).
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- Users
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."Users" (
  id        bigint generated by default as identity primary key,
  email     text not null unique,
  role      text not null default 'USER',
  created_at timestamptz not null default now(),
  google_id text unique
);

comment on table public."Users" is 'Stores all of the user data';

-- ─────────────────────────────────────────────────────────────────────────────
-- Videos
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."Videos" (
  id           text primary key,
  title        text,
  description  text,
  duration     numeric,
  thumbnail    text,
  date_uploaded timestamptz,
  created_at   timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- HeadShots
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."HeadShots" (
  id         uuid primary key default gen_random_uuid(),
  url        text not null,
  created_at timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- ThumbnailJob
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."ThumbnailJob" (
  id                          bigint generated by default as identity primary key,
  video_title                 text,
  video_url                   text,
  status                      text,
  thumbnail                   text,
  notes                       text,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamp default now(),
  suggested_thumbnails        text[],
  thumbnail_suggestion_status text,
  favorite                    boolean not null default false,
  deleted_at                  timestamp
);

comment on table public."ThumbnailJob" is 'Are table to store all of the';

-- ─────────────────────────────────────────────────────────────────────────────
-- ThumbnailComments
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."ThumbnailComments" (
  id              bigint generated by default as identity primary key,
  thumbnail_job_id bigint not null references public."ThumbnailJob"(id),
  text            text not null,
  attachments     jsonb[],
  author_name     text,
  author_email    text,
  created_at      timestamptz not null default now(),
  author_image    text
);

-- ─────────────────────────────────────────────────────────────────────────────
-- ChatConversations
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."ChatConversations" (
  id          uuid primary key default gen_random_uuid(),
  email       text,
  title       text,
  model       text,
  is_pinned   boolean,
  is_archived boolean,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz default now(),
  google_id   text
);

-- ─────────────────────────────────────────────────────────────────────────────
-- ChatMessages
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."ChatMessages" (
  id              uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public."ChatConversations"(id),
  role            text not null,
  content         text not null,
  token_count     numeric,
  created_at      timestamptz not null default now(),
  metadata        jsonb
);

-- ─────────────────────────────────────────────────────────────────────────────
-- LearningPillars
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."LearningPillars" (
  id          uuid primary key default gen_random_uuid(),
  slug        text not null unique,
  name        text not null,
  description text,
  icon_name   text,
  order_index integer default 0,
  created_at  timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- LearningTopics
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."LearningTopics" (
  id          uuid primary key default gen_random_uuid(),
  pillar_id   uuid not null references public."LearningPillars"(id),
  slug        text not null,
  name        text not null,
  description text,
  order_index integer default 0,
  created_at  timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- InterviewQuestions
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."InterviewQuestions" (
  id                   uuid primary key default gen_random_uuid(),
  name                 text not null unique,
  leetcode_number      integer,
  difficulty           text not null check (difficulty = any (array['Easy','Medium','Hard'])),
  prompt_full          text not null,
  starter_code         text not null,
  helper_code          text not null default '',
  test_cases           jsonb not null default '[]',
  video_ids            text[] default '{}',
  created_at           timestamptz default now(),
  source               text[] not null default '{}',
  category             text,
  pattern              text,
  leetcode_url         text,
  order_index          integer,
  concept_slug         text,
  concept_slugs_backup text[]
);

-- ─────────────────────────────────────────────────────────────────────────────
-- LearningArticles
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."LearningArticles" (
  id                   uuid primary key default gen_random_uuid(),
  topic_id             uuid not null references public."LearningTopics"(id),
  slug                 text not null,
  title                text not null,
  excerpt              text,
  body                 text not null,
  reading_time_minutes integer default 5,
  is_premium           boolean not null default false,
  is_published         boolean not null default false,
  order_index          integer default 0,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  concept_tags         jsonb not null default '[]',
  primary_concept      text,
  practice_question_id uuid references public."InterviewQuestions"(id),
  audio_url            text
);

comment on column public."LearningArticles".audio_url is 'Public URL of pre-generated TTS MP3 for listen-to-article.';

-- ─────────────────────────────────────────────────────────────────────────────
-- UserArticleProgress
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."UserArticleProgress" (
  id          uuid primary key default gen_random_uuid(),
  email       text not null,
  article_id  uuid not null references public."LearningArticles"(id),
  completed_at timestamptz not null default now(),
  created_at  timestamptz not null default now(),
  google_id   text
);

alter table public."UserArticleProgress" enable row level security;

-- ─────────────────────────────────────────────────────────────────────────────
-- UserBookmarks
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."UserBookmarks" (
  id         uuid primary key default gen_random_uuid(),
  email      text not null,
  article_id uuid not null references public."LearningArticles"(id),
  created_at timestamptz not null default now(),
  google_id  text
);

alter table public."UserBookmarks" enable row level security;

-- ─────────────────────────────────────────────────────────────────────────────
-- Concepts
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."Concepts" (
  id          uuid primary key default gen_random_uuid(),
  slug        text not null unique,
  label       text not null,
  short_label text,
  description text,
  track_slug  text not null,
  kind        text not null default 'concept',
  created_at  timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- ConceptDependencies
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."ConceptDependencies" (
  track_slug      text not null,
  concept_slug    text not null references public."Concepts"(slug),
  depends_on_slug text not null references public."Concepts"(slug),
  weight          smallint not null default 1,
  created_at      timestamptz not null default now(),
  primary key (concept_slug, depends_on_slug)
);

-- add concept_slug FK to InterviewQuestions now that Concepts exists
-- (IF NOT EXISTS is not supported on ADD CONSTRAINT — use a DO block)
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'InterviewQuestions_concept_slug_fkey'
  ) then
    alter table public."InterviewQuestions"
      add constraint "InterviewQuestions_concept_slug_fkey"
      foreign key (concept_slug) references public."Concepts"(slug);
  end if;
end $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- UserConceptStats
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."UserConceptStats" (
  email             text not null,
  track_slug        text not null,
  concept_slug      text not null references public."Concepts"(slug),
  exposures         integer not null default 0,
  internalized_count integer not null default 0,
  last_seen_at      timestamptz,
  google_id         text,
  primary key (email, track_slug, concept_slug)
);

alter table public."UserConceptStats" enable row level security;

-- ─────────────────────────────────────────────────────────────────────────────
-- TelemetryEvents
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."TelemetryEvents" (
  id         uuid primary key default gen_random_uuid(),
  email      text not null,
  track_slug text not null,
  session_id text not null,
  event_type text not null,
  mode       text not null,
  payload    jsonb not null default '{}',
  dedupe_key text unique,
  created_at timestamptz not null default now(),
  google_id  text
);

alter table public."TelemetryEvents" enable row level security;

-- ─────────────────────────────────────────────────────────────────────────────
-- UserInternalizations
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."UserInternalizations" (
  id             uuid primary key default gen_random_uuid(),
  session_id     uuid not null,
  email          text not null,
  picked         text not null check (picked = any (array['A','B','FREEFORM','learned','clarified'])),
  concept_slug   text not null,
  note           text,
  delta_snapshot jsonb not null default '{}',
  created_at     timestamptz not null default now(),
  track_slug     text not null,
  google_id      text
);

alter table public."UserInternalizations" enable row level security;

-- ─────────────────────────────────────────────────────────────────────────────
-- UserFeedback
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."UserFeedback" (
  id           text primary key,
  created_at   timestamptz not null default now(),
  category     text not null check (category = any (array['bug','idea','content','other'])),
  message      text not null check (char_length(message) >= 10 and char_length(message) <= 2000),
  page_path    text,
  contact_email text,
  user_email   text,
  google_id    text,
  user_agent   text,
  status       text not null default 'new' check (status = any (array['new','reviewing','closed'])),
  metadata     jsonb not null default '{}'
);

alter table public."UserFeedback" enable row level security;

-- ─────────────────────────────────────────────────────────────────────────────
-- TestSession
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."TestSession" (
  id               bigint generated by default as identity primary key,
  started_at       timestamptz,
  completed_at     timestamptz,
  total_questions  bigint,
  correct_answers  bigint,
  score_percentage numeric,
  created_at       timestamptz not null default now(),
  email            text,
  google_id        text
);

-- ─────────────────────────────────────────────────────────────────────────────
-- TestAnswer
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."TestAnswer" (
  id          bigint generated by default as identity primary key,
  session_id  bigint references public."TestSession"(id),
  question_id uuid references public."InterviewQuestions"(id),
  answer      text,
  is_correct  boolean,
  created_at  timestamptz not null default now(),
  email       text,
  google_id   text
);

-- ─────────────────────────────────────────────────────────────────────────────
-- SessionAIDecisions
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."SessionAIDecisions" (
  id             uuid primary key default gen_random_uuid(),
  created_at     timestamptz not null default now(),
  decision_type  text not null,
  decision_mode  text not null,
  track_slug     text not null,
  step_index     integer,
  actor_email    text not null,
  model          text not null,
  prompt_version text not null,
  confidence     numeric,
  rationale      text,
  input_json     jsonb not null default '{}',
  output_json    jsonb not null default '{}',
  applied        boolean not null default true,
  source         text not null default 'session_intelligence',
  dedupe_key     text,
  session_id     text,
  decision_scope text,
  decision_target text,
  fallback_used  boolean not null default false,
  latency_ms     integer,
  error_code     text
);

-- ─────────────────────────────────────────────────────────────────────────────
-- LiveQuestions
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."LiveQuestions" (
  id          uuid primary key default gen_random_uuid(),
  body        text not null,
  user_email  text,
  user_name   text,
  is_answered boolean not null default false,
  is_pinned   boolean not null default false,
  created_at  timestamptz not null default now(),
  google_id   text
);

-- ─────────────────────────────────────────────────────────────────────────────
-- LiveQuestionVotes
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public."LiveQuestionVotes" (
  id          uuid primary key default gen_random_uuid(),
  question_id uuid not null references public."LiveQuestions"(id) on delete cascade,
  user_email  text,
  created_at  timestamptz not null default now(),
  google_id   text,
  unique (question_id, user_email)
);
